### ISSUE TITLE
timber function

### ISSUE THREAD

**Issue by CrazyJ1984** [bear989/GT5u-Bears-Den#7]
fix the timber function for the chainsaws

**Comment by diregarath** [comment]
@CrazyJ1984 This is the old project - the new one is here.  https://github.com/BearsDen989-GT/Gregtech-5u-Bears-Den-Edition - I sent you an invite to be a member of the github organization there as well.

**Comment by diregarath** [comment]
Created new issue here - https://github.com/BearsDen989-GT/Gregtech-5u-Bears-Den-Edition/issues/22 - closing this.
